---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность заказывать товары, добавленные в корзину
  - Для фильтрации товаров должны быть указаны определённые критерии - бренд, цена и т.д.
  - Товары должны корректно фильтроваться как по отдельному критерию, так и по нескольким сразу
  - Фильтр по цене должен учитывать граничные значения
  - Фильтры должны иметь возможность сброса
  - Веб-сайт должен соответствовать положениям законодательства
  - Веб-сайт должен быть представлен в русской и английской версии
  - Пользователь должен иметь возможность редактировать корзину - удалять товары, настраивать кол-во того или иного заказываемого товара
