---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Все имеющиеся фильтры товаров должны иметь корректную функцию сброса
  - Веб-сайт должен соответствовать положениям законодательства
  - Веб-сайт должен быть корректно переведён на языки пользователей ЦА (целевой аудитории)
  - Веб-сайт должен запрашивать у пользователей необходимую контактную информацию (номер телефона, эл. почта)
  - Пользователь должен иметь возможность редактировать корзину (удалять товары, настраивать кол-во того или иного заказываемого товара)
  - В поле бренд должны высвечиваться только те бренды, которые соответствуют выбранной категории товаров
